// Deploys Heirloom to the selected network and regenerates web/src/lib/contracts.ts
// from every deployments/<network>.json.   Usage: hardhat run scripts/deploy.js --network localhost|amoy
const fs = require("fs");
const path = require("path");
const hre = require("hardhat");

const DEPLOYMENTS = path.join(__dirname, "..", "deployments");
const OUT = path.join(__dirname, "..", "..", "web", "src", "lib", "contracts.ts");

function writeContractsTs(abi) {
  const deployments = {};
  for (const f of fs.readdirSync(DEPLOYMENTS).filter((f) => f.endsWith(".json"))) {
    const d = JSON.parse(fs.readFileSync(path.join(DEPLOYMENTS, f), "utf8"));
    deployments[d.chainId] = { address: d.address, startBlock: d.startBlock };
  }
  const ts = `// Generated by contracts/scripts/deploy.js - do not edit.
export const heirloomAbi = ${JSON.stringify(abi, null, 2)} as const;

export const heirloomDeployments = ${JSON.stringify(deployments, null, 2)} as const;
`;
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, ts);
}

async function main() {
  const [deployer] = await hre.ethers.getSigners();
  if (!deployer) throw new Error("No deployer account. For amoy set DEPLOYER_PRIVATE_KEY (and AMOY_RPC_URL).");
  const { chainId } = await hre.ethers.provider.getNetwork();

  const factory = await hre.ethers.getContractFactory("Heirloom");
  const contract = await factory.deploy();
  const receipt = await contract.deploymentTransaction().wait();
  const address = await contract.getAddress();

  fs.mkdirSync(DEPLOYMENTS, { recursive: true });
  fs.writeFileSync(
    path.join(DEPLOYMENTS, `${hre.network.name}.json`),
    JSON.stringify({ chainId: Number(chainId), address, startBlock: receipt.blockNumber, deployer: deployer.address }, null, 2)
  );
  writeContractsTs(JSON.parse(factory.interface.formatJson()));
  console.log(`Heirloom deployed to ${address} on ${hre.network.name} (chainId ${chainId}, block ${receipt.blockNumber})`);
}

main().catch((e) => {
  console.error(e);
  process.exitCode = 1;
});
