// Deploys Heirloom (and its Anon Aadhaar verifier) to the selected network and regenerates web/src/lib/contracts.ts
// from every deployments/<network>.json.   Usage: hardhat run scripts/deploy.js --network localhost|sepolia|amoy
//
// Identity verifier, chosen by environment:
//   (default)                       deploy the official Groth16 Verifier + AnonAadhaar from @anon-aadhaar/contracts.
//   ANON_AADHAAR_MODE=test|real     which UIDAI public key the verifier trusts: "test" (default) accepts only test QR codes
//                                   made with the published test key; "real" accepts only genuine UIDAI-signed Aadhaar QR codes.
//   ANON_AADHAAR_VERIFIER=0x...     use an already deployed AnonAadhaar contract instead of deploying one.
//   ANON_AADHAAR_VERIFIER=none      no verifier: identity features are disabled on this deployment.
//   ANON_AADHAAR_VERIFIER=mock      deploy the TEST DOUBLE (accepts "proofs" that merely commit to the public inputs). Local
//                                   chains only; refused everywhere else.
//   ANON_AADHAAR_NULLIFIER_SEED     this app's nullifier seed (default: keccak256("heirloom.anon-aadhaar.v1") >> 8).
const fs = require("fs");
const path = require("path");
const hre = require("hardhat");
const { testPublicKeyHash, productionPublicKeyHash } = require("@anon-aadhaar/core");

const DEPLOYMENTS = path.join(__dirname, "..", "deployments");
const OUT = path.join(__dirname, "..", "..", "web", "src", "lib", "contracts.ts");
const BACKEND_CHAIN = path.join(__dirname, "..", "..", "backend", "chain");

function writeContractsTs(abi) {
  const deployments = {};
  for (const f of fs.readdirSync(DEPLOYMENTS).filter((f) => f.endsWith(".json"))) {
    const d = JSON.parse(fs.readFileSync(path.join(DEPLOYMENTS, f), "utf8"));
    deployments[d.chainId] = { address: d.address, startBlock: d.startBlock, anonAadhaar: d.anonAadhaar, anonAadhaarMode: d.anonAadhaarMode, nullifierSeed: d.nullifierSeed };
  }
  const ts = `// Generated by contracts/scripts/deploy.js - do not edit.
export const heirloomAbi = ${JSON.stringify(abi, null, 2)} as const;

export const heirloomDeployments = ${JSON.stringify(deployments, null, 2)} as const;
`;
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, ts);
}

// Local chains start empty every time. Top up your own wallet(s) so MetaMask never shows a fee warning.
// Addresses come from FUND_ADDRESSES (comma-separated) and/or contracts/fund.local.json (a JSON array; gitignored).
async function fundLocalWallets() {
  const list = [...(process.env.FUND_ADDRESSES ? process.env.FUND_ADDRESSES.split(",") : [])];
  const file = path.join(__dirname, "..", "fund.local.json");
  if (fs.existsSync(file)) list.push(...JSON.parse(fs.readFileSync(file, "utf8")));
  for (const raw of list.map((a) => a.trim()).filter(Boolean)) {
    const addr = hre.ethers.getAddress(raw);
    await hre.network.provider.send("hardhat_setBalance", [addr, "0x" + (10_000n * 10n ** 18n).toString(16)]);
    console.log(`Funded ${addr} with 10000 test ETH`);
  }
}

// The backend indexer reads the ABI and the deployed addresses from backend/chain/ (merged per chain id).
function writeBackendChain(abi, chainId, address, startBlock) {
  fs.mkdirSync(BACKEND_CHAIN, { recursive: true });
  fs.writeFileSync(path.join(BACKEND_CHAIN, "Heirloom.abi.json"), JSON.stringify(abi, null, 1));
  const file = path.join(BACKEND_CHAIN, "deployments.json");
  const all = fs.existsSync(file) ? JSON.parse(fs.readFileSync(file, "utf8")) : {};
  all[chainId] = { address, startBlock };
  fs.writeFileSync(file, JSON.stringify(all, null, 2));
}

async function deployVerifier(chainId) {
  const choice = (process.env.ANON_AADHAAR_VERIFIER || "").trim();
  const local = ["localhost", "hardhat"].includes(hre.network.name);
  if (choice === "none") return { address: hre.ethers.ZeroAddress, mode: "none" };
  if (choice === "mock") {
    if (!local) throw new Error("ANON_AADHAAR_VERIFIER=mock is a test double and is refused on public networks.");
    const mock = await (await hre.ethers.getContractFactory("MockAnonAadhaar")).deploy();
    await mock.waitForDeployment();
    console.log("WARNING: deployed the MOCK Anon Aadhaar verifier. Proofs are not verified cryptographically.");
    return { address: await mock.getAddress(), mode: "mock" };
  }
  if (choice) return { address: hre.ethers.getAddress(choice), mode: "custom" };

  const mode = (process.env.ANON_AADHAAR_MODE || "test").toLowerCase();
  if (!["test", "real"].includes(mode)) throw new Error('ANON_AADHAAR_MODE must be "test" or "real".');
  const pubkeyHash = mode === "real" ? productionPublicKeyHash : testPublicKeyHash;
  const groth16 = await (await hre.ethers.getContractFactory("Verifier")).deploy();
  await groth16.waitForDeployment();
  const anon = await (await hre.ethers.getContractFactory("AnonAadhaar")).deploy(await groth16.getAddress(), pubkeyHash);
  await anon.waitForDeployment();
  console.log(`Deployed Anon Aadhaar verifier (${mode} public key) on chain ${chainId}.`);
  return { address: await anon.getAddress(), mode };
}

async function main() {
  const [deployer] = await hre.ethers.getSigners();
  if (!deployer) throw new Error("No deployer account. For amoy set DEPLOYER_PRIVATE_KEY (and AMOY_RPC_URL).");
  const { chainId } = await hre.ethers.provider.getNetwork();

  const verifier = await deployVerifier(chainId);
  const seed = BigInt(process.env.ANON_AADHAAR_NULLIFIER_SEED || BigInt(hre.ethers.id("heirloom.anon-aadhaar.v1")) >> 8n);

  const factory = await hre.ethers.getContractFactory("Heirloom");
  const contract = await factory.deploy(verifier.address, seed);
  const receipt = await contract.deploymentTransaction().wait();
  const address = await contract.getAddress();

  fs.mkdirSync(DEPLOYMENTS, { recursive: true });
  fs.writeFileSync(
    path.join(DEPLOYMENTS, `${hre.network.name}.json`),
    JSON.stringify(
      {
        chainId: Number(chainId), address, startBlock: receipt.blockNumber, deployer: deployer.address,
        anonAadhaar: verifier.address, anonAadhaarMode: verifier.mode, nullifierSeed: seed.toString(),
      },
      null,
      2
    )
  );
  writeContractsTs(JSON.parse(factory.interface.formatJson()));
  writeBackendChain(JSON.parse(factory.interface.formatJson()), Number(chainId), address, receipt.blockNumber);
  if (["localhost", "hardhat"].includes(hre.network.name)) await fundLocalWallets();
  console.log(`Heirloom deployed to ${address} on ${hre.network.name} (chainId ${chainId}, block ${receipt.blockNumber}); identity verifier: ${verifier.mode}`);
}

main().catch((e) => {
  console.error(e);
  process.exitCode = 1;
});
