// Deploys Heirloom to the selected network and regenerates web/src/lib/contracts.ts
// from every deployments/<network>.json.   Usage: hardhat run scripts/deploy.js --network localhost|amoy
const fs = require("fs");
const path = require("path");
const hre = require("hardhat");

const DEPLOYMENTS = path.join(__dirname, "..", "deployments");
const OUT = path.join(__dirname, "..", "..", "web", "src", "lib", "contracts.ts");
const BACKEND_CHAIN = path.join(__dirname, "..", "..", "backend", "chain");

function writeContractsTs(abi) {
  const deployments = {};
  for (const f of fs.readdirSync(DEPLOYMENTS).filter((f) => f.endsWith(".json"))) {
    const d = JSON.parse(fs.readFileSync(path.join(DEPLOYMENTS, f), "utf8"));
    deployments[d.chainId] = { address: d.address, startBlock: d.startBlock };
  }
  const ts = `// Generated by contracts/scripts/deploy.js - do not edit.
export const heirloomAbi = ${JSON.stringify(abi, null, 2)} as const;

export const heirloomDeployments = ${JSON.stringify(deployments, null, 2)} as const;
`;
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, ts);
}

// Local chains start empty every time. Top up your own wallet(s) so MetaMask never shows a fee warning.
// Addresses come from FUND_ADDRESSES (comma-separated) and/or contracts/fund.local.json (a JSON array; gitignored).
async function fundLocalWallets() {
  const list = [...(process.env.FUND_ADDRESSES ? process.env.FUND_ADDRESSES.split(",") : [])];
  const file = path.join(__dirname, "..", "fund.local.json");
  if (fs.existsSync(file)) list.push(...JSON.parse(fs.readFileSync(file, "utf8")));
  for (const raw of list.map((a) => a.trim()).filter(Boolean)) {
    const addr = hre.ethers.getAddress(raw);
    await hre.network.provider.send("hardhat_setBalance", [addr, "0x" + (10_000n * 10n ** 18n).toString(16)]);
    console.log(`Funded ${addr} with 10000 test ETH`);
  }
}

// The backend indexer reads the ABI and the deployed addresses from backend/chain/ (merged per chain id).
function writeBackendChain(abi, chainId, address, startBlock) {
  fs.mkdirSync(BACKEND_CHAIN, { recursive: true });
  fs.writeFileSync(path.join(BACKEND_CHAIN, "Heirloom.abi.json"), JSON.stringify(abi, null, 1));
  const file = path.join(BACKEND_CHAIN, "deployments.json");
  const all = fs.existsSync(file) ? JSON.parse(fs.readFileSync(file, "utf8")) : {};
  all[chainId] = { address, startBlock };
  fs.writeFileSync(file, JSON.stringify(all, null, 2));
}

async function main() {
  const [deployer] = await hre.ethers.getSigners();
  if (!deployer) throw new Error("No deployer account. For amoy set DEPLOYER_PRIVATE_KEY (and AMOY_RPC_URL).");
  const { chainId } = await hre.ethers.provider.getNetwork();

  const factory = await hre.ethers.getContractFactory("Heirloom");
  const contract = await factory.deploy();
  const receipt = await contract.deploymentTransaction().wait();
  const address = await contract.getAddress();

  fs.mkdirSync(DEPLOYMENTS, { recursive: true });
  fs.writeFileSync(
    path.join(DEPLOYMENTS, `${hre.network.name}.json`),
    JSON.stringify({ chainId: Number(chainId), address, startBlock: receipt.blockNumber, deployer: deployer.address }, null, 2)
  );
  writeContractsTs(JSON.parse(factory.interface.formatJson()));
  writeBackendChain(JSON.parse(factory.interface.formatJson()), Number(chainId), address, receipt.blockNumber);
  if (["localhost", "hardhat"].includes(hre.network.name)) await fundLocalWallets();
  console.log(`Heirloom deployed to ${address} on ${hre.network.name} (chainId ${chainId}, block ${receipt.blockNumber})`);
}

main().catch((e) => {
  console.error(e);
  process.exitCode = 1;
});
