# Generated by Django 5.2.17 on 2026-10-03 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("indexer", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=40)),
                ("title", models.CharField(max_length=160)),
                ("body", models.TextField()),
                ("urgent", models.BooleanField(default=False)),
                ("view", models.CharField(default="owner", max_length=20)),
                ("chain_id", models.PositiveIntegerField(blank=True, null=True)),
                ("asset_id", models.BigIntegerField(blank=True, null=True)),
                ("claim_id", models.BigIntegerField(blank=True, null=True)),
                ("dedupe_key", models.CharField(max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("email_attempts", models.PositiveSmallIntegerField(default=0)),
                ("email_error", models.TextField(blank=True)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="indexer.chainevent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["user", "read_at"],
                        name="notificatio_user_id_47e85c_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "dedupe_key"), name="one_notification_per_key"
                    )
                ],
            },
        ),
    ]
