// Maintains and checks the message catalogues in src/messages/<locale>/<area>.json.
//   node scripts/i18n.mjs index   regenerate src/messages/<locale>/index.ts (merges every area file)
//   node scripts/i18n.mjs check   every locale has the same areas and keys as English, with the same {placeholders} and <tags>;
//                                 and no text-bearing JSX attribute is a hardcoded string
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { parse } from "@formatjs/icu-messageformat-parser";

const src = path.join(path.dirname(fileURLToPath(import.meta.url)), "..", "src");
const root = path.join(src, "messages");
const LOCALES = ["en", "hi", "bn"];
// The PDF audit report is always English (its fonts cannot draw other scripts), so this catalogue exists only in English.
const EN_ONLY = ["report"];
const areas = (l) => fs.readdirSync(path.join(root, l)).filter((f) => f.endsWith(".json")).map((f) => f.slice(0, -5)).filter((a) => l === "en" || !EN_ONLY.includes(a)).sort();

function index() {
  for (const l of LOCALES) {
    const names = areas(l);
    const imp = names.map((n, i) => `import a${i} from "./${n}.json";`).join("\n");
    const body = names.map((_, i) => `  ...a${i},`).join("\n");
    fs.writeFileSync(path.join(root, l, "index.ts"), `// Generated by scripts/i18n.mjs index. Do not edit.\n${imp}\n\nconst messages = {\n${body}\n};\n\nexport default messages;\n`);
  }
}

const flatten = (o, p = "") => Object.entries(o).flatMap(([k, v]) => (v && typeof v === "object" ? flatten(v, `${p}${k}.`) : [[`${p}${k}`, v]]));
const readArea = (l, a) => flatten(JSON.parse(fs.readFileSync(path.join(root, l, `${a}.json`), "utf8")));
const load = (l) => Object.fromEntries(areas(l).flatMap((a) => readArea(l, a)));

// The arguments and rich-text tags a message uses, found with the real ICU parser (so plural/select branches are not mistaken for arguments).
const tokens = (msg) => {
  const found = new Set();
  const walk = (nodes) => {
    for (const n of nodes) {
      if ([1, 2, 3, 4].includes(n.type)) found.add(n.value); // argument, number, date, time
      if (n.type === 5 || n.type === 6) { found.add(n.value); Object.values(n.options).forEach((o) => walk(o.value)); } // select, plural
      if (n.type === 8) { found.add(`<${n.value}>`); walk(n.children); } // tag
    }
  };
  walk(parse(String(msg)));
  return [...found].sort().join(",");
};

const tsxFiles = (d) => fs.readdirSync(d, { withFileTypes: true }).flatMap((e) => (e.isDirectory() ? tsxFiles(path.join(d, e.name)) : e.name.endsWith(".tsx") ? [path.join(d, e.name)] : []));
const LINE_BREAK = new RegExp("\\r?\\n");
const ATTR = /\b(placeholder|title|aria-label|alt|label|text|hint|intro|actionLabel|message)=("[^"{}]*[A-Za-z]{2,}[^"]*"|\{"[^"]*[A-Za-z]{2,}[^"]*"\})/g;

function check() {
  const en = load("en");
  let bad = 0;
  const fail = (m) => { bad++; console.error("i18n:", m); };
  const enOnly = new Set(EN_ONLY.flatMap((a) => readArea("en", a).map(([k]) => k)));
  for (const l of LOCALES.filter((x) => x !== "en")) {
    const cur = load(l);
    for (const k of Object.keys(en)) {
      if (enOnly.has(k)) continue;
      if (!(k in cur)) fail(`${l}: missing ${k}`);
      else if (tokens(en[k]) !== tokens(cur[k])) fail(`${l}: placeholders/tags differ in ${k}: "${tokens(en[k])}" vs "${tokens(cur[k])}"`);
      else if (!String(cur[k]).trim()) fail(`${l}: empty ${k}`);
    }
    for (const k of Object.keys(cur)) if (!(k in en)) fail(`${l}: extra key ${k} (not in English)`);
  }
  // Text hidden in attributes (placeholder, title, aria-label...) must come from the catalogue too; the JSX text rule covers children.
  for (const f of tsxFiles(src)) {
    fs.readFileSync(f, "utf8").split(LINE_BREAK).forEach((line, i) => {
      for (const m of line.matchAll(ATTR)) fail(`${path.relative(src, f)}:${i + 1}: hardcoded ${m[1]}=${m[2]}`);
    });
  }
  if (bad) process.exit(1);
  console.log(`i18n: ${Object.keys(en).length} messages, ${LOCALES.length} languages, all in sync`);
}

const cmd = { index, check }[process.argv[2]];
if (!cmd) {
  console.error("usage: i18n.mjs index|check");
  process.exit(2);
}
cmd();
