# Generated by Django 5.2.17 on 2026-10-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChainEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chain_id", models.PositiveIntegerField()),
                ("address", models.CharField(max_length=42)),
                ("block_number", models.BigIntegerField()),
                ("block_hash", models.CharField(max_length=66)),
                ("timestamp", models.BigIntegerField()),
                ("tx_hash", models.CharField(max_length=66)),
                ("log_index", models.PositiveIntegerField()),
                ("event_name", models.CharField(max_length=40)),
                ("args", models.JSONField()),
                ("tx_from", models.CharField(blank=True, max_length=42)),
                ("asset_id", models.BigIntegerField(blank=True, null=True)),
                ("claim_id", models.BigIntegerField(blank=True, null=True)),
                ("owner", models.CharField(blank=True, max_length=42)),
                ("participants", models.TextField(blank=True)),
                ("processed", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["block_number", "log_index"],
                "indexes": [
                    models.Index(
                        fields=["chain_id", "address", "block_number", "log_index"],
                        name="indexer_cha_chain_i_c63bf6_idx",
                    ),
                    models.Index(
                        fields=["chain_id", "address", "asset_id"],
                        name="indexer_cha_chain_i_e38a97_idx",
                    ),
                    models.Index(
                        fields=["chain_id", "address", "claim_id"],
                        name="indexer_cha_chain_i_1cf96e_idx",
                    ),
                    models.Index(
                        fields=["chain_id", "address", "owner", "event_name"],
                        name="indexer_cha_chain_i_4c39e6_idx",
                    ),
                    models.Index(
                        fields=["processed"], name="indexer_cha_process_c1cc01_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("chain_id", "tx_hash", "log_index"), name="unique_log"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="IndexerState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chain_id", models.PositiveIntegerField()),
                ("address", models.CharField(max_length=42)),
                ("last_block", models.BigIntegerField()),
                ("last_block_hash", models.CharField(blank=True, max_length=66)),
                ("head_block", models.BigIntegerField(default=0)),
                ("head_time", models.BigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_error", models.TextField(blank=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("chain_id", "address"), name="one_state_per_deployment"
                    )
                ],
            },
        ),
    ]
