// Shared by deploy.js and deploy-test-token.js: regenerates web/src/lib/contracts.ts from deployments/*.json (+ tokens/*.json).
const fs = require("fs");
const path = require("path");

const DEPLOYMENTS = path.join(__dirname, "..", "..", "deployments");
const TOKENS = path.join(DEPLOYMENTS, "tokens");
const OUT = path.join(__dirname, "..", "..", "..", "web", "src", "lib", "contracts.ts");

const readDir = (dir) => (fs.existsSync(dir) ? fs.readdirSync(dir).filter((f) => f.endsWith(".json")).map((f) => JSON.parse(fs.readFileSync(path.join(dir, f), "utf8"))) : []);

function writeContractsTs(abi) {
  const deployments = {};
  for (const d of readDir(DEPLOYMENTS)) {
    deployments[d.chainId] = { address: d.address, startBlock: d.startBlock, anonAadhaar: d.anonAadhaar, anonAadhaarMode: d.anonAadhaarMode, nullifierSeed: d.nullifierSeed };
  }
  const testTokens = {};
  for (const t of readDir(TOKENS)) testTokens[t.chainId] = { address: t.address, symbol: t.symbol, name: t.name, decimals: t.decimals };
  const ts = `// Generated by contracts/scripts - do not edit.
export const heirloomAbi = ${JSON.stringify(abi, null, 2)} as const;

export const heirloomDeployments = ${JSON.stringify(deployments, null, 2)} as const;

/** Faucet test token (HTT) per chain. Test networks only: it is deployed by deploy-test-token.js, never on mainnet. */
export const testTokens = ${JSON.stringify(testTokens, null, 2)} as const;
`;
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, ts);
}

/** Deploys TestToken with the current signer and records it. Returns the record. */
async function deployTestToken(hre, abi) {
  const [deployer] = await hre.ethers.getSigners();
  if (!deployer) throw new Error("No deployer account. For amoy set DEPLOYER_PRIVATE_KEY (and AMOY_RPC_URL).");
  const { chainId } = await hre.ethers.provider.getNetwork();
  const token = await (await hre.ethers.getContractFactory("TestToken")).deploy();
  const receipt = await token.deploymentTransaction().wait();
  const record = {
    chainId: Number(chainId), address: await token.getAddress(), symbol: await token.symbol(), name: await token.name(),
    decimals: Number(await token.decimals()), startBlock: receipt.blockNumber, deployer: deployer.address,
  };
  fs.mkdirSync(TOKENS, { recursive: true });
  fs.writeFileSync(path.join(TOKENS, `${hre.network.name}.json`), JSON.stringify(record, null, 2));
  if (abi) writeContractsTs(abi);
  return record;
}

module.exports = { writeContractsTs, deployTestToken };
