// Generated by scripts/i18n.mjs index. Do not edit.
import a0 from "./account.json";
import a1 from "./audit.json";
import a2 from "./beneficiary.json";
import a3 from "./claims.json";
import a4 from "./flows.json";
import a5 from "./gate.json";
import a6 from "./identity.json";
import a7 from "./landing.json";
import a8 from "./lib.json";
import a9 from "./owner.json";
import a10 from "./people.json";
import a11 from "./report.json";
import a12 from "./security.json";
import a13 from "./shared.json";

const messages = {
  ...a0,
  ...a1,
  ...a2,
  ...a3,
  ...a4,
  ...a5,
  ...a6,
  ...a7,
  ...a8,
  ...a9,
  ...a10,
  ...a11,
  ...a12,
  ...a13,
};

export default messages;
